spring:
  profiles: dev
  datasource:
    name: bid
    # url: jdbc:mysql://192.168.40.239:3306/v2_bid?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=true
    url: jdbc:mysql://192.168.40.239:3306/useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=true
    username: develop
    password: ENC(zxdr+EZmduSn4L0bsWeJ0zgL7zqKE0tNcD7TTXM88Lw=)

  redis:
    database: 9
    host: 192.168.40.239
    port: 6379
    password: ENC(WO5Jiz/gAmFUcVWFRNcuZ34LyjzGlPD+)
    timeout: 2000
    jedis:
      pool:
        max-active: 1024
        max-idle: 200
        max-wait: 1000
        min-idle: 200
        testOnBorrow: true
        testOnReturn: true

jasypt:
  encryptor:
    password: 2&%$$#@$*
