#营销服务
url:
  marketing:
    article:
      articleList: /publicize/article/getArticleList
      getArticle: /publicize/article/getArticle
      articleAddReq: /publicize/article/addArticle
      updateArticle: /publicize/article/updateArticle
      stickTopArticle: /publicize/article/stickTopArticle
      deleteArticle: /publicize/article/deleteArticle
    friendLink:
      getFriendLinkList: /publicize/friendLink/getFriendLinkList
      getFriendLink: /publicize/friendLink/getFriendLink
      addFriendLink: /publicize/friendLink/addFriendLink
      updateFriendLink: /publicize/friendLink/updateFriendLink
      deleteFriendLink: /publicize/friendLink/deleteFriendLink
    post:
      getPostList: /publicize/post/getPostList
      getPost: /publicize/post/getPost
      addPost: /publicize/post/addPost
      updatePost: /publicize/post/updatePost
      stickTopPost: /publicize/post/stickTopPost
      deletePost: /publicize/post/deletePost
##用户服务
##借款用户列表
#user.borrowerList = /borrower/list
##拉黑或取消拉黑接口
#user.defriend = /borrower/defriend
##个人借款信息
#user.personalInfo = /borrower/personalInfo
##企业借款信息
#user.enterpriseInfo = /borrower/enterpriseInfo
##借款记录
#user.loanList = /borrower/loanList
##借款信息
#user.loanInfo = /borrower/loanInfo
##注销账户
#user.destroy = /borrower/destroy
##修改个人借款人资料
#user.updatePersonalInfo = /borrower/updatePersonalInfo
##修改企业借款人资料
#user.updateEnterpriseInfo = borrower/updateEnterpriseInfo