# common configuration
server:
  port: 7111
  compression:
    enabled: true

spring:
  profiles:
    active: dev

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: com/fenlibao/pms/mapper/**/*.xml

pms:
  permitUrls:
    - /api/auth/**
  swaggerUrls:
    - /swagger-ui.html
    - /swagger-resources/**
    - /images/**
    - /webjars/**
    - /v2/api-docs
  securityUrls:
    - /configuration/ui
    - /configuration/security
    - /
    - /csrf
  excludeUri:
    - swagger
    - csrf
    - error
  example:
    test: test
  request:
    salt: b1695b17-f8ef-4221-99ae-af58604d4369