# common configuration
server:
  port: 7002
  compression:
    enabled: true

spring:
  profiles:
    active: dev

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: com/fenlibao/marketing/mapper/**/*.xml

marketing:
  permitUrls:
    - /api/auth/**
    - /swagger-ui.html
    - /swagger-resources/**
    - /images/**
    - /webjars/**
    - /v2/api-docs
    - /configuration/ui
    - /configuration/security
    - /
    - /csrf
  example:
    test: test